### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by ghost** [phpstan/playground#1]
I've been using phpstan.org a bit recently, just having a few requests on minorish improvements :)

- link from phpstan.org to phpstan/phpstan (mostly because the .org domain comes up as autocomplete now, instead of jumping to search engine results for the term "phpstan")
- link from phpstan.org to phpstan/playground (because reasons)
- max attribute of the input[type="number"] to possibly be linked to a const in phpstan/phpstan (because there isn't a level > 7 at the moment?

**Comment by ondrejmirtes** [comment]
I think most of these points no longer apply.
