### ISSUE TITLE
Where did version selector and parameters text area go?

### ISSUE THREAD

**Issue by meridius** [phpstan/playground#14]
The website always had version selector and parameters text area as shown on the picture:
![](https://user-images.githubusercontent.com/175109/28476683-2bb8a37a-6e51-11e7-9e24-459467fdfc18.png)

It is not there now. Why? I miss it a lot.

**Comment by ondrejmirtes** [comment]
Hi,
I was losing a lot of money, running the playground project on AWS. I rewrote it to be cloud native in a day (using S3 and AWS Lambda). It for example allowed me to add "strict rules" option for the first time.

I'd like to hear - what was your use case to run the same code under different versions? I'd like to be able to add it back but maybe in a different shape - like comparing "dev-master" output against the latest stable with a single click of a button, or something like that. The old way with the selectbox was too unrestricted, I'd like to hear how people used it.

The same goes for parameters - what did you change the most?
