### ISSUE TITLE
Trait causes no errors

### ISSUE THREAD

**Issue by adaamz** [phpstan/playground#3]
for example undefined variable gives no error
https://phpstan.org/r/eff8b9f22bcd296c2f3a9e0f6ef9596b

**Comment by JanTvrdik** [comment]
I still have no idea why does this happen. Feel free to debug it yourself and send PR. My best guess is that this it's some odd phpstan bug.

**Comment by CZechBoY** [comment]
I think that php parser is broken or idk.
CodeSanitizer::26 where is 
```php
$allNodes = $this->parser->parse($code);
```
then `$allNodes` contains statement with Trait, which contains ClassMethod which contains *no* statements.

I think phpstan is not doing this (why it should...) and this is the difference.
What do you think?

**Comment by CZechBoY** [comment]
OK, I found first problem is that every statements from ClassMethod and Function are cleared out in `App\Model\CodeSanitizer` on lines 57-64. https://github.com/phpstan/playground/blob/97168f71ad47537ef70904a6b44a26d0f56382ef/app/model/CodeSanitizer.php#L57-64
If I remove that code I still get no error - and in pure phpstan command there is too without error.
So I need to create empty class which uses this trait. Then I get error about `Undefined variable: $var`.

@JanTvrdik What do you think about first problem and second problem?
The second problem is problem in phpstan itself, so I probably create issue there.

**Comment by ondrejmirtes** [comment]
Traits are analysed in context of each class that uses them: https://phpstan.org/r/6c98defa-7057-4b3a-a15b-2b2ea5111037 (I also fixed a bug that forgot to set `NodeScopeResolver::setAnalysedFiles()` in the playground.)
