### ISSUE TITLE
The level selector should have a max level

### ISSUE THREAD

**Issue by stof** [phpstan/playground#6]
The level selector in the UI should have a `max` attribute so that the browser does not let you increment it higher than the max phpstan level.

**Comment by Majkl578** [comment]
The input should have range 0-<max> restriction.
It would also be nice to allow string value "max".

**Comment by stof** [comment]
the 0 restriction is already there. The `<input type="number">` already has its `min` attribute set.

Allowing `max` as a string would force to move away from a number input.

**Comment by JanTvrdik** [comment]
Maximum level depends on selected version. So the version and level inputs would need to be swapped. Also phpstan provides no CLI API to fetch max level. It can only be guessed by looking into `conf` directory, but there is no guarantee, that this approach will work in future versions.

**Comment by stof** [comment]
Well, even if some level does not work for some versions, that's still fine (the interface will display a warning saying the config is not found). but I would at least put a max to the highest level available among all versions.

**Comment by stof** [comment]
Closing as the new playground implemented that.
