### ISSUE TITLE
Install more PHP extensions

### ISSUE THREAD

**Issue by Majkl578** [phpstan/playground#8]
I wanted to make an example with GMP not working in arithmetic operations, but it turns out playground doesn't have GMP installed: https://phpstan.org/r/39aeec691d53190e039aaf7af64ecb7b
Would be nice to add at least _standard_ PHP extensions (those that are part of PHP itself).

**Comment by JanTvrdik** [comment]
@Majkl578 I installed couple more, hope that's enough for now.

~~~
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
imap
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
pspell
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
~~~
